# Name of the GitHub Action
name: Generate Snake Contribution Graph

# Controls when the action will run.
on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Allows manual runs from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository's code
      - uses: actions/checkout@v4

      # Step 2: Generate the snake animation files
      - uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: SHADOW2669
          
          # Add '?palette=github-dark' to generate the dark theme version
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?palette=github-dark

      # Step 3: Commit and push the generated files to the 'output' branch
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # The directory that contains the files to be pushed
          build_dir: dist
          # The branch to which the files will be pushed
          target_branch: output
        env:
          # The GITHUB_TOKEN is required for authentication to push to the branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
