# .github/workflows/update_stats.yml

name: Update Portfolio Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1
        
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch and update stats
        env:
          THM_USERNAME: ${{ secrets.THM_USERNAME }}
          HTB_API_KEY: ${{ secrets.HTB_API_KEY }}
          HTB_USER_ID: ${{ secrets.HTB_USER_ID }}
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          MONKEYTYPE_USERNAME: ${{ secrets.MONKEYTYPE_USERNAME }}
        run: python fetch_stats.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "📊 Automated stats update" && git push)